# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-17 08:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sittings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('committee', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('election_year', models.CharField(max_length=100)),
                ('links', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
    ]
