# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 06:28
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('councilors', '0005_auto_20170322_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('birth', models.DateField(blank=True, null=True)),
                ('former_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=None, null=True, size=None)),
                ('identifiers', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=70, unique=True)),
                ('councilor_terms', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('election_year', models.CharField(db_index=True, max_length=100)),
                ('number', models.IntegerField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('party', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('constituency', models.IntegerField(db_index=True)),
                ('county', models.CharField(db_index=True, max_length=100)),
                ('district', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('votes', models.IntegerField(blank=True, null=True)),
                ('votes_percentage', models.CharField(blank=True, max_length=100, null=True)),
                ('elected', models.NullBooleanField(db_index=True)),
                ('contact_details', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('links', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('platform', models.TextField(blank=True, null=True)),
                ('politicalcontributions', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.Candidates', to_field=b'uid')),
                ('elected_councilor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elected_candidate', to='councilors.CouncilorsDetail')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='terms',
            unique_together=set([('candidate', 'election_year')]),
        ),
        migrations.AlterIndexTogether(
            name='terms',
            index_together=set([('election_year', 'county', 'constituency')]),
        ),
    ]
