# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-30 12:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('councilors', '0005_auto_20170322_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_election_year', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('election_year', models.CharField(db_index=True, max_length=100)),
                ('number', models.IntegerField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('party', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('constituency', models.IntegerField(db_index=True)),
                ('county', models.CharField(db_index=True, max_length=100)),
                ('district', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('votes', models.IntegerField(blank=True, null=True)),
                ('votes_percentage', models.CharField(blank=True, max_length=100, null=True)),
                ('elected', models.NullBooleanField(db_index=True)),
                ('contact_details', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('links', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('platform', models.TextField(blank=True, null=True)),
                ('politicalcontributions', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('councilor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elected_candidate', to='councilors.Councilors', to_field=b'uid')),
            ],
        ),
    ]
