# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 16:11
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('councilor_terms', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('election_year', models.CharField(db_index=True, default=b'2018', max_length=4)),
                ('likes', models.IntegerField(db_index=True, default=0)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('party', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('constituency', models.IntegerField(db_index=True)),
                ('county', models.CharField(db_index=True, max_length=100)),
                ('district', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('contact_details', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('links', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('platform', models.TextField(blank=True, null=True)),
                ('politicalcontributions', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candidates.Candidates', to_field=b'uid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='terms',
            name='birth',
        ),
        migrations.AlterUniqueTogether(
            name='intent',
            unique_together=set([('user', 'election_year')]),
        ),
        migrations.AlterIndexTogether(
            name='intent',
            index_together=set([('election_year', 'county', 'constituency')]),
        ),
    ]
