# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-04 09:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_intent_likes_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intent',
            name='links',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='\u7db2\u7ad9'),
        ),
        migrations.AlterField(
            model_name='intent',
            name='motivation',
            field=models.TextField(blank=True, null=True, verbose_name='\u70ba\u4ec0\u9ebc\u5831\u540d'),
        ),
    ]
