# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 06:43
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_create_data_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='intent_likes',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
