# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_intent_likes_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='intent_likes',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
