# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_candidates_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='intent',
            name='slogan',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u6a19\u8a9e'),
        ),
        migrations.AddField(
            model_name='intent',
            name='video_link',
            field=models.URLField(blank=True, null=True, verbose_name='\u5f71\u7247'),
        ),
    ]
