# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_intent_slogan_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='intent',
            name='type',
            field=models.CharField(db_index=True, default='councilors', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='terms',
            name='type',
            field=models.CharField(db_index=True, default='councilors', max_length=20),
            preserve_default=False,
        ),
    ]
