# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0013_add_occupy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intent',
            name='constituency',
            field=models.IntegerField(db_index=True, verbose_name='\u9078\u8209\u5340'),
        ),
        migrations.AlterField(
            model_name='intent',
            name='type',
            field=models.CharField(db_index=True, max_length=20, verbose_name='\u7af6\u9078\u8077\u4f4d'),
        ),
    ]
