# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0014_auto_20180515_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='intent',
            name='ideology',
            field=models.TextField(blank=True, null=True, verbose_name='\u653f\u6cbb\u7406\u5ff5'),
        ),
        migrations.AlterField(
            model_name='intent',
            name='platform',
            field=models.TextField(blank=True, null=True, verbose_name='\u5730\u65b9\u653f\u898b'),
        ),
    ]
