# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0004_auto_20180607_0824'),
        ('candidates', '0016_auto_20180531_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='intent_standpoints',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intent_standpoints', to='platforms.Platforms', to_field=b'uid'),
        ),
    ]
