# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0017_intent_standpoints_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='intent',
            name='candidate_term',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intent', to='candidates.Terms'),
        ),
    ]
