# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0018_intent_candidate_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intent',
            name='candidate_term',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intent', to='candidates.Terms', to_field=b'uid'),
        ),
    ]
