# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-08 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0021_auto_20180808_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_generate_list',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='\u5019\u9078\u4eba\u540d\u5b57'),
        ),
        migrations.AddField(
            model_name='user_generate_list',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='\u5916\u90e8\u7db2\u5740'),
        ),
        migrations.AlterField(
            model_name='user_generate_list',
            name='recommend',
            field=models.NullBooleanField(db_index=True, verbose_name='\u60a8\u63a8\u85a6\u9019\u4efd\u540d\u55ae\uff1f'),
        ),
    ]
