# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0022_auto_20180808_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intent',
            name='district',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='terms',
            name='district',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
