# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-17 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=30)),
                ('valid', models.BooleanField()),
                ('hits', models.IntegerField()),
            ],
        ),
    ]
