# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-04 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_keyword_county'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='keyword',
            unique_together=set([('content', 'county', 'category')]),
        ),
    ]
