# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 09:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('standpoints', '0002_standpoints_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='standpoints',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_standpoints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user_standpoint',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='user_standpoint',
            unique_together=set([('user', 'standpoint')]),
        ),
    ]
