# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-17 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bills',
            old_name='links',
            new_name='link',
        ),
    ]
