# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 04:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('councilors', '0005_auto_20170322_1055'),
        ('bills', '0003_bills_links'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='councilors_bills',
            unique_together=set([('councilor', 'bill')]),
        ),
    ]
