# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mayors', '0002_terms_in_office'),
        ('bills', '0004_auto_20170718_0437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mayors_Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.Bills', to_field=b'uid')),
                ('mayor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mayors.Terms', to_field=b'uid')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='mayors_bills',
            unique_together=set([('mayor', 'bill')]),
        ),
    ]
