# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-17 08:24
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sittings', '__first__'),
        ('councilors', '0005_auto_20170322_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Councilors_Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.IntegerField(blank=True, null=True)),
                ('conflict', models.NullBooleanField()),
                ('councilor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='councilors.CouncilorsDetail')),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=110, unique=True)),
                ('vote_seq', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('conflict', models.NullBooleanField()),
                ('result', models.CharField(blank=True, max_length=50, null=True)),
                ('results', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('sitting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='sittings.Sittings', to_field=b'uid')),
                ('voter', models.ManyToManyField(through='votes.Councilors_Votes', to='councilors.CouncilorsDetail')),
            ],
        ),
        migrations.AddField(
            model_name='councilors_votes',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.Votes', to_field=b'uid'),
        ),
    ]
