# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 04:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('councilors', '0005_auto_20170322_1055'),
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='councilors_votes',
            unique_together=set([('councilor', 'vote')]),
        ),
    ]
