# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 10:10
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('checked', models.BooleanField(db_index=True, default=False)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='achievements',
            unique_together=set([('user', 'name')]),
        ),
        migrations.AlterIndexTogether(
            name='achievements',
            index_together=set([('user', 'checked')]),
        ),
    ]
