# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 11:20
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Platforms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('county', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='\u7e23\u5e02')),
                ('content', models.TextField(verbose_name='\u653f\u898b')),
                ('likes', models.IntegerField(db_index=True, default=0)),
                ('references', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('status', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Platforms_Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platforms.Platforms', to_field=b'uid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='platforms_likes',
            unique_together=set([('platform', 'user')]),
        ),
        migrations.AlterIndexTogether(
            name='platforms_likes',
            index_together=set([('platform', 'user')]),
        ),
    ]
