# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('councilors', '0006_councilors_data'),
        ('candidates', '0016_auto_20180531_1514'),
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platforms',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candidates.Terms', to_field=b'uid'),
        ),
        migrations.AddField(
            model_name='platforms',
            name='councilor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='councilors.CouncilorsDetail'),
        ),
        migrations.AddField(
            model_name='platforms',
            name='intent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candidates.Intent', to_field=b'uid'),
        ),
        migrations.AlterField(
            model_name='platforms',
            name='content',
            field=models.TextField(verbose_name='\u9858\u671b'),
        ),
    ]
