# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mayors', '0002_terms_in_office'),
        ('platforms', '0002_auto_20180531_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='platforms',
            name='mayor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mayors.Terms', to_field=b'uid', verbose_name='\u7e23\u5e02\u9577'),
        ),
        migrations.AlterField(
            model_name='platforms',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candidates.Terms', to_field=b'uid', verbose_name='\u5019\u9078\u4eba'),
        ),
        migrations.AlterField(
            model_name='platforms',
            name='councilor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='councilors.CouncilorsDetail', verbose_name='\u7e23\u5e02\u8b70\u54e1'),
        ),
        migrations.AlterField(
            model_name='platforms',
            name='intent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candidates.Intent', to_field=b'uid', verbose_name='\u64ec\u53c3\u9078\u4eba'),
        ),
    ]
