# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-09 07:28
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sittings', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Councilors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('birth', models.DateField(blank=True, null=True)),
                ('former_names', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CouncilorsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_year', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('party', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('constituency', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('county', models.CharField(db_index=True, max_length=100)),
                ('district', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('in_office', models.BooleanField(db_index=True)),
                ('contact_details', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('term_start', models.DateField(blank=True, null=True)),
                ('term_end', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('links', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('social_media', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('platform', models.TextField(blank=True, null=True)),
                ('param', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('councilor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='each_terms', to='councilors.Councilors', to_field=b'uid')),
            ],
        ),
        migrations.CreateModel(
            name='FileLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitting', models.CharField(max_length=100, unique=True)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PoliticalContributions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_individual', models.IntegerField(blank=True, null=True)),
                ('in_profit', models.IntegerField(blank=True, null=True)),
                ('in_party', models.IntegerField(blank=True, null=True)),
                ('in_civil', models.IntegerField(blank=True, null=True)),
                ('in_anonymous', models.IntegerField(blank=True, null=True)),
                ('in_others', models.IntegerField(blank=True, null=True)),
                ('in_total', models.IntegerField(blank=True, null=True)),
                ('out_personnel', models.IntegerField(blank=True, null=True)),
                ('out_propagate', models.IntegerField(blank=True, null=True)),
                ('out_campaign_vehicle', models.IntegerField(blank=True, null=True)),
                ('out_campaign_office', models.IntegerField(blank=True, null=True)),
                ('out_rally', models.IntegerField(blank=True, null=True)),
                ('out_travel', models.IntegerField(blank=True, null=True)),
                ('out_miscellaneous', models.IntegerField(blank=True, null=True)),
                ('out_return', models.IntegerField(blank=True, null=True)),
                ('out_exchequer', models.IntegerField(blank=True, null=True)),
                ('out_public_relation', models.IntegerField(blank=True, null=True)),
                ('out_total', models.IntegerField(blank=True, null=True)),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('councilor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='politicalcontributions', to='councilors.CouncilorsDetail')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='councilor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='councilors.CouncilorsDetail'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='sitting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sittings.Sittings', to_field=b'uid'),
        ),
    ]
