# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-09 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councilors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='councilorsdetail',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
