# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-22 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councilors', '0004_auto_20170320_1351'),
    ]

    operations = [
        migrations.RunSQL("UPDATE councilors_councilorsdetail SET constituency = null WHERE constituency = '';"),
        migrations.RunSQL("DROP INDEX public.councilors_councilorsdetail_constituency_like;"),
        migrations.AlterField(
            model_name='councilorsdetail',
            name='constituency',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
