# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councilors', '0006_councilors_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='councilorsdetail',
            name='district',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
