# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-20 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('councilors', '0004_auto_20170320_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Councilors_Suggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiction', models.NullBooleanField(db_index=True)),
                ('councilor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='councilors.CouncilorsDetail')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, max_length=100, unique=True)),
                ('county', models.CharField(db_index=True, max_length=100)),
                ('election_year', models.CharField(db_index=True, max_length=4)),
                ('suggest_year', models.CharField(db_index=True, max_length=4)),
                ('suggest_month', models.CharField(db_index=True, max_length=2)),
                ('suggestion', models.TextField()),
                ('position', models.TextField(blank=True, null=True)),
                ('suggest_expense', models.IntegerField(blank=True, null=True)),
                ('approved_expense', models.IntegerField(blank=True, null=True)),
                ('expend_on', models.TextField(blank=True, null=True)),
                ('brought_by', models.TextField(blank=True, null=True)),
                ('bid_type', models.TextField(blank=True, null=True)),
                ('bid_by', models.TextField(blank=True, null=True)),
                ('district', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('constituency', models.IntegerField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='councilors_suggestions',
            name='suggestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='councilors', to='suggestions.Suggestions', to_field=b'uid'),
        ),
    ]
