# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-20 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='councilors_suggestions',
            unique_together=set([('councilor', 'suggestion')]),
        ),
    ]
