# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-20 15:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0002_auto_20170320_1555'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE suggestions_suggestions ALTER COLUMN bid_by TYPE JSONB USING jsonb_build_array(bid_by);'),
    ]
