# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-29 13:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0003_auto_20170320_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestions',
            name='approved_expense_avg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suggestions',
            name='suggest_expense_avg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suggestions',
            name='bid_by',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
