# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 14:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suggestions', '0005_suggestions_suggestor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Suggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro', models.BooleanField(db_index=True, verbose_name='\u8d0a\u6210')),
                ('grade', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suggestions.Suggestions', to_field=b'uid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='user_suggestions',
            unique_together=set([('user', 'suggestion')]),
        ),
        migrations.AlterIndexTogether(
            name='user_suggestions',
            index_together=set([('user', 'suggestion')]),
        ),
    ]
